version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    restart: always

  proxy:
    image: nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - appnet
    restart: always
    depends_on:
      - web

  web:
    image: molarmanful/realaf
    ports:
      - 3000:3000/tcp
      - 20000-20100:20000-20100/udp
    networks:
      - appnet
    restart: always
