version: '3.8'

services:
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
    restart: always

  proxy:
    image: nginxproxy/nginx-proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
    restart: always

  web:
    image: molarmanful/realaf
    ports:
      - 80:80/tcp
      - 20000-20100:20000-20100/udp
    environment:
      - VIRTUAL_HOST=realaf.ninja
    restart: always
