version: '3.8'
services:
  web:
    image: molarmanful/realaf:latest
    ports:
      - "3000:3000/tcp"
      - "20000-20100:20000-20100/udp"
    restart: always
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /root/.docker/config.json:/config.json
    command: --interval 30
