# yaml-language-server: $schema=http://json-schema.org/draft-07/schema

name: DEPLOY

on: push

concurrency:
  group: deploy
  cancel-in-progress: true

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - uses: docker/build-push-action@v3
        with:
          push: true
          tags: molarmanful/realaf:latest
